set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix
bind-key c new-window -c "#{pane_current_path}"
bind-key Left swap-window -d -t -1
bind-key Right swap-window -d -t +1
set-option -g mouse on
unbind-key -n MouseDown3Pane
unbind-key -n M-MouseDown3Pane
set-option -g status off
set-option -g set-titles on
set-option -g set-titles-string "#{pane_title}"
set-option -g exit-empty off
set-option -g detach-on-destroy no-detached
set-window-option -g mode-keys vi
set-option -sa terminal-overrides ',xterm-256color:RGB'
